### ISSUE TITLE
Create tutorials

### ISSUE THREAD

**Issue by emhart** [GotelliLab/EcoSimR#17]
Convert the tutorials in use_tutorials to knitr vignettes.

**Comment by emhart** [comment]
On top of this, we probably want to add two major tutorials.

- [ ] On how to use set-seed for reproducibility
- [ ] On adding your own metrics and algos.

**Comment by emhart** [comment]
@ngotelli If you want to create vignettes, probably the best thing is to just use vignettes template from rstudio (file > new > RMarkdown > from template)  Here's some documentation: http://rmarkdown.rstudio.com/package_vignette_format.html

I'll worry about the integration with the package and the webpage.

**Comment by ngotelli** [comment]
@emhart I pushed the corrected version of the co-occurrence vignette, which should be integrated with the docs page. You may want to edit the figures as you did in the other vignettes so that they look nicer than the R vignette template. Thanks!
