### ISSUE TITLE
Change set.seed behavior

### ISSUE THREAD

**Issue by emhart** [GotelliLab/EcoSimR#28]
@davharris pointed out that the way we have set.seed() in the function reduces entropy.  A better practice is to just set the seed at the beginning of the session.  Will have to give a think on this and possibly change

**Comment by davharris** [comment]
Thanks @emhart.  Specifically, the default random number generator has something like 20,000 bits of entropy (it's based on 624 32-bit integers).

Setting the seed based on *one* 32-bit integer thus potentially reduces the entropy by a factor of 600 or so.

Also, the more times this happens, the lower the entropy gets.  You can see the effects of this pretty clearly using the following code:

```
set.seed(0)
x = numeric(1000000)
for(i in 1:length(x)){
  set.seed(trunc(runif(1,-2000000000,2000000000)))
  x[i] = runif(1)
}
length(unique(x)) / length(x)
```

Only 20% of the "random" numbers generated are unique because the RNG keeps visiting the same states.  If I comment out the `set.seed` line, I get 99.99% unique values, and the resulting distribution looks much more uniform when plotted as a histogram with 100 bins.

**Comment by ngotelli** [comment]
Dave, you are right, our use of `set.seed()` is indeed limiting the range of random seeds. What I was trying to do was to generate a completely reproducible set of output from EcoSimR, including the random number seed that generated the run. But I could never figure out a way to pull out the integer seed from a session unless `set.seed()` was called first. Therefore, I set up the input so that a user could supply a seed, but if one was not supplied, the program provided one "under the table". This seed then shows up in the output so that the run can be reproduced. I guess we could just delete this hack entirely, but I would still like to be able to provide the seed that was used even if the user doesn't give one at the start of the session. I'd be grateful if you have a better solution to this problem. Thanks! Nick

**Comment by davharris** [comment]
You can get (and save) the current random seed using `.Random.seed`.

```
> old.seed = .Random.seed

> runif(1)
[1] 0.4358815

> set.seed(old.seed)

> runif(1)
[1] 0.4358815
```

**Comment by ngotelli** [comment]
Many thanks, David. I did not know about `.Random.seed`, which will indeed store the current random seed. But because it is an integer vector, it does not appear to be something I can return to the user as printed output to recreate the run by passing it to `set.seed`. 

I will keep reading...

**Comment by davharris** [comment]
Couldn't the seed still be stored as part of the output object, even if it wasn't printed? The user could still get it with null_model$seed if they needed it. 

If you want to show the user information about the seed every time, but don't want to show the whole thing, you could just show a hash of it. That way, the user could quickly tell if two runs had different seeds, but you don't have to fill their screen with 20000 bits of seed. 

Dave

**Comment by ngotelli** [comment]
I like this solution. Thanks!

    Nick

    Quoting "David J. Harris" <notifications@github.com>:
>
> Couldn't the seed still be stored as part of the output object, even  
> if it wasn't printed? The user could still get it with  
> null_model$seed if they needed it.
>
>    If you want to show the user information about the seed every  
> time, but don't want to show the whole thing, you could just show a  
> hash of it. That way, the user could quickly tell if two runs had  
> different seeds, but you don't have to fill their screen with 20000  
> bits of seed.
>
>    Dave
>
>    > On Jan 28, 2015, at 5:01 PM, Nick Gotelli  
> <notifications@github.com> wrote:
>    >
>    > Many thanks, David. I did not know about .Random.seed, which  
> will indeed store the current random seed. But because it is an  
> integer vector, it does not appear to be something I can return to  
> the user as printed output to recreate the run by passing it to  
> set.seed.
>    >
>    > I will keep reading...
>    >
>    > —
>    > Reply to this email directly or view it on GitHub.
>    >
>
> —
>    Reply to this email directly or view it on GitHub[1].
>  
>
>

 
********************************************************
    Nicholas J. Gotelli       Office Phone: 802-656-0450
    Department of Biology     Lab Phone: 802-656-0451   
    University of Vermont     Fax: 802-656-2914
    Burlington, VT 05405      e-mail: ngotelli@uvm.edu
    ********************************************************
    Home Page (with manuscript pdfs):
http://www.uvm.edu/~ngotelli/homepage.html

    Musician's Corner (with mp3s):
http://www.uvm.edu/~ngotelli/musicpage/music.html

    NEW: EcoSimR (free software for null model analysis):
http://www.uvm.edu/~ngotelli/EcoSim/EcoSim.html
    ********************************************************



Links:
------
[1] https://github.com/GotelliLab/EcoSimR/issues/28#issuecomment-71955712

**Comment by emhart** [comment]
Ok, I think I fixed this issue.  Now the user simply says if they want to save the seed or not.  Then if the seed is saved the user can reproduce the model.  I wrote a special little helper called `reproduce_model()` that extracts the saved seed and sets it.  This is because `set.seed()` doesn't work with the full vector.

The advantage is that if all model runs save the seed they can all be reproduced.  Here's a small example.

```R
finchMod <- cooc_null_model(wiFinches, algo="sim1", saveSeed = T)
mean(finchMod$Sim)
 
reproduce_model(finchMod$Sim)

finchMod <- cooc_null_model(wiFinches, algo="sim1")
## Check model output is the same as before
 mean(finchMod$Sim)
```

**Comment by amellison17** [comment]
This is a very nice fix, and I especially like the reproduce_model() function!

**Comment by amellison17** [comment]
Ted, can you send me or post somewhere I can easily find it reproduce_model()? I would like to cite it in a book chapter I'm working on.
Thanks!
Aaron

**Comment by emhart** [comment]
@amellison17 Probably you could just cite the whole package.  What we can do with the first release is get a DOI for the package (https://guides.github.com/activities/citable-code/) and then you could just cite that.  My guess is that we're just a few weeks away from a first release.  Would that work?  

The code itself for reproduce model is just a couple of lines: https://github.com/GotelliLab/EcoSimR/blob/master/R/reproduce_model.R

Really its how that function interacts with the objects we create that is the nifty part (I think anyway).
The way it works is simple.  If you say you want to save the seed, then the model run grabs the current random seed and stores it as part of the null model object.  When you say you want to reproduce the model, all that's actually happening is the little helper function reads the seed from the object and then sets that seed.  The advantage is that this avoids the attenuation of randomness that @davharris pointed out above while remaining reproducible.  Also it means that the user doesn't have to keep track of various seeds, and there can be many models in your R session, all of which are easily reproducible without a loss of randomness or having to remember what seed you set for what model.

Does that answer your question?

**Comment by amellison17** [comment]
Ted , that will work fine for citing (it will be a while before the book is out). And I like the solution!

**Comment by ngotelli** [comment]
Yes, this is the best solution possible. The only part of it that is less
than optimal is that the results are reproducible only if the data object
has been saved. If the results are summarized and sent to a .csv output
file, you can't go back and reproduce it. That being said, the original
solution definitely truncated the range of possible random number seeds,
which was not good. This solution binds the seed to the object, which is
excellent. Interestingly, I bet that most users also severely truncate the
range of random number seeds whenver they use the set.seed() function, by
picking some rather small positive integer.

    Quoting Aaron Ellison <notifications@github.com>:
>
> Ted , that will work fine for citing (it will be a while before the  
> book is out). And I like the solution!
>
> —
>    Reply to this email directly or view it on GitHub[1].
>  
>
>

 
********************************************************
    Nicholas J. Gotelli       Office Phone: 802-656-0450
    Department of Biology     Lab Phone: 802-656-0451   
    University of Vermont     Fax: 802-656-2914
    Burlington, VT 05405      e-mail: ngotelli@uvm.edu
    ********************************************************
    Home Page (with manuscript pdfs):
http://www.uvm.edu/~ngotelli/homepage.html

    Musician's Corner (with mp3s):
http://www.uvm.edu/~ngotelli/musicpage/music.html

    NEW: EcoSimR (free software for null model analysis):
http://www.uvm.edu/~ngotelli/EcoSim/EcoSim.html
    ********************************************************



Links:
------
[1] https://github.com/GotelliLab/EcoSimR/issues/28#issuecomment-73928462

**Comment by emhart** [comment]
I'd actually thought about that a bit Nick.  One solution down the road would be to think about a minimal amount of metadata that could be published along with a model.  The seed is a bit unwieldy because it will be a vector of length 626.  I wonder if this could be dumped into EML, or perhaps another standard.  This is worth some thought and I'll ping some folks about it.  I'm going to close this for now and we can reopen another issue with the broader context of how to store the metadata for the model.
