### ISSUE TITLE
Now using MASS library for gamma function in size overlap

### ISSUE THREAD

**Issue by ngotelli** [GotelliLab/EcoSimR#39]
I looked at my code for the gamma distribution and decided to use the MLE estimator of the shape and rate parameters that are produced with the `fitdistr` function in the MASS library. Aaron and I decided early on we would try to not call any other libraries (e.g. ggplot), but the MASS library should be on all R distributions, so I don't think this will be an issue. However, the MASS library is now loaded from within the function, and you probably want to move that up to load initially as a dependency when EcoSimR is loaded.

That brings up another issue, which is that the structure of null_model_engine (at least as we originally built it) introduces a lot of unnecessary calculation inside the functions. Each algorithm has passed to it only an empirical data matrix, and sometimes additional data vectors for weights. All calculations are made inside the function to generate a random data matrix.

This means that the same parameters calculated from the data set are re-calculated every time the algorithm is called to produce a new random matrix. In this case, we are getting the MLE estimators from the same empirical data every time we generate a new randomized data set. But that really isn't necessary. Ideally we should calculate the needed parameters once at the start, and then pass those to the function along with the data. For example, in `gamma_size`, we pass only the speciesData vector. But the algorithm would run faster if we passed the data and 3 constants:
```r
speciesData
n = length(speciesData)
a = shape  # shape parameter for gamma estimated from fitdistr applied to speciesData
b = rate     # rate parameter for gamma estimated from fitdistr applied to speciesData
```
Although our method is slower, we probably want to keep it the way it is. Otherwise, we would have to reprogram the `null_model_engine`, which could be complicated. More important, by doing all the parameter calculations within the function, it can be used outside of `null_model_engine` so it is a lot more portable.

**Comment by emhart** [comment]
I agree with your assessment @ngotelli ,  I ran a quick profile of the code on a data set bigger than we'd ever encounter in real life.    I didn't see any serious difference, here are the results.
```R
library(lineprof)

size_gamma <- function (speciesData=rnorm(50,mean=100,sd=1)) {
  
  mleFit <- fitdistr(speciesData, 'gamma')
  a <- mleFit$estimate["shape"]
  b <- mleFit$estimate["rate"]
  gammaDraw <- rgamma(length(speciesData),shape=a,rate=b)
  
  return(gammaDraw)
}

dat <- rgamma(5000,20,.3)

sg <-  lineprof(rep(size_gamma(speciesData = dat),100000))

time   alloc release dups          ref                 src
1 0.026   0.508   0.000  312           #3 size_gamma/fitdistr
2 0.001   0.001   0.000   71           #6 size_gamma/rgamma  
3 2.200 476.837   0.671    0 character(0)               


mleFit <- fitdistr(dat, 'gamma')
a <- mleFit$estimate["shape"]
b <- mleFit$estimate["rate"]

size_gamma2 <- function (speciesData=rnorm(50,mean=100,sd=1),a,b) {
  gammaDraw <- rgamma(length(speciesData),shape=a,rate=b)
  
  return(gammaDraw)
}

sgfast <-  lineprof(rep(size_gamma2(speciesData = dat,a,b),100000))
time alloc release dups          ref src
1 2.149     0       0    0 character(0)    


```

**Comment by emhart** [comment]
Also, one more thought I had about this is that we could write these out to the namespace if we really wanted to, and then just use an if statement to check on them.  But I think in this case there's not enough of a performance hit for it to really matter.  

The other issue is how people will create user defined fxn's.  However I think that's a bit too far off to be concerned about.
