### ISSUE TITLE
Improved C-score and related metrics.

### ISSUE THREAD

**Issue by ngotelli** [GotelliLab/EcoSimR#43]
We should definitely implement @davharris code for calculating the `c_score`, but restore line 369, which is the error check for empty rows.

Once this is done we should then modify the code for `c_score.skew` and `c_score.var` so that they call `c_score`. The error check needs to live only in `c_score`, not in these other functions.

@emhart how do I pull in @davharris fork in GitHub to get the new function?

**Comment by davharris** [comment]
My pull request is at #31.  I think there will be a button that says "merge" to bring it in, if you decide to do so.

**Comment by emhart** [comment]
Successfully merged @davharris pr

**Comment by ngotelli** [comment]
Thank you @davharris  and @emhart !
