### ISSUE TITLE
Convert docs to saticdocs webpage

### ISSUE THREAD

**Issue by emhart** [GotelliLab/EcoSimR#5]
Build a webpage, possibly host it on gh-pages, using http://staticdocs.had.co.nz/dev/

**Comment by emhart** [comment]
@ngotelli and @amellison17 As we're approaching the release, I wanted to run the basics of the webpage by you guys.  You can see a draft here: http://gotellilab.github.io/EcoSimR/inst/web/index.html  It's based on the same stuff that Hadley uses for all his pages,e.g. http://docs.ggplot2.org/current/  I'll probably move the quick start out of the beginning and put that into a basic vignette to more closely resemble ggplot2.

**Comment by amellison17** [comment]
@emhart Website looks good. I do like the Hadley help interface a bit more than the standard R.

**Comment by ngotelli** [comment]
Excellent, I really like the style and layout. 

I have completed documentation on all of the underlying metrics and algorithms. Over the next few days, I will double-check this material and also add documentation for the other functions (graphs, etc.) that are in the package. Ted, sorry about the name changes on the size ratio algorithms, but I wanted to be consistent with names so that we have clusters of algorithms that are used for co-occurrence (sim), niche overlap (ra), and now size ratios (size). When they are named this way, they all pop up in a cluster when you search in the help system, which is very useful.

Ted, should I work up vignettes for each of the models? Is there a template or structure I should be using?

**Comment by emhart** [comment]
Great idea about changing the names Nick.  I think working up a vignette will be great at this point.  I'm almost done with writing all the tests.   I think I have another issue on vignettes so I'll respond over there.

**Comment by emhart** [comment]
@ngotelli I think we are now very close.  I'd like to spend some time spiffing up the webpage.  It looks like we've got the most of the documentation set-up.  One thing to think about is what you want the domain to be.  We could register our own domain and have it point to the pages here.  Some might be https://domains.google.com/registrar?s=ecosimR&_ga=1.122107212.69167048.1425494045#tld=com,info,net,ninja,org,solar,support&chp=tld

I'd happily cover the $12 fee and then we could have a custom domain like ecosimr.org or ecosimr.info

Or we could just set-up a new ecosimr group, and then fork the repo over to there.  Then the webpage would be ecosimr.github.io.  

Or you could use your own domain like gotelli.info and then have it be a subdomain like ecosimr.gotelli.info

I think it's nice to have a simple high level domain though with no paths.  That way someone can just go to ecosimr.info and then find all the documentation.  I also think it adds a level of gravitas to the project.  Do you have any preferences?

**Comment by amellison17** [comment]
@emhart I vote for ecosimr.org

**Comment by ngotelli** [comment]
@emhart I also think `ecosimr.org` is good. I am happy to pick up the cost. I have finished all of the testing and annotating of all the basic algorithms and metrics. There are a few other functions in there and data descriptions that I need to write, as well as some vignettes. I will try to do all this as soon as I can. Do we have a deadline for this as far as the Ecography article or other deadlines with CRAN?

**Comment by emhart** [comment]
@ngotelli @amellison17 We don't have any deadlines other than self-imposed.  Michael told me that EcoSimR was probably not a great fit for the special issue because it was focused on software that was a tool that facilitated reproducibility, not did something reproducibly.  E.g. A package that captures work flow provenance vs a package that calculates a metric.

Regarding the domain, I beat you to it, but you're welcome to buy me a beer next time we meet :beers: :smile:   I just pushed up the latest version to the new domain.  I'm hosting it off of my own web server at the moment if you guys are ok with that.  You can see it at http://ecosimr.org.

I'll work on the web page, but we should have it up and running before your workshop in April.  What are the dates on that Nick?

Thanks for your feedback.

**Comment by ngotelli** [comment]
@emhart . That's too bad we can't include EcoSimR in Michael's special issue. But doesn't Ecography publish software descriptions of single packages? I doubt we could get something in to MEE without a novel new method to offer (but could be something in the future). My workshop in Switzerland is the third week of April, so I would still like to push ahead on this.

I wrote much of the niche overlap tutorial tonight, but I can't get the vignette markdown template to compile any code inside of `dev tools`. I even tried getting out of `dev_tools` and sourcing all of the script files in the general environment and loading the `.rda` data file. It all works in the console, but the `.Rmd` file is not seeing any of this. Is there any way to fix this? I haven't pushed anything up yet.

That is just fine that you purchased the domain; I checked on it last night and noticed you were signed up. Ted, you've done an incredible job with this package; there is no way Aaron and I could have taken it to this level. Next time I see you :beers: or :wine_glass: or :cocktail: or :sake: are on me! :+1: :grinning:

**Comment by emhart** [comment]
@ngotelli Why don't you push the tutorial to the repo and I'll try and see what's going on with rendering it.

Also I've update the webpage:  I'm breaking it out into sections: http://ecosimr.org

Currently I'm doing Niche, Size and Co-Occurrence null models.  However we could break it out by
Metrics, Algorithms and Null model engines.  

Also I'm setting it up so all plotting examples run when the webpage is built. e.g. http://ecosimr.org/niche_null_model.html

**Comment by ngotelli** [comment]
Thanks @emhart . I thought I could solve this by adding and committing the change locally, but that didn't do it, so I pushed it to the repo. I notice now that my  .Rmd vignette file is not in the R subfolder. Perhaps that's the reason? Or does it need to live in the man subfolder?

**Comment by emhart** [comment]
@ngotelli I fixed up your vignette.  All you need to do is make sure the files are in the "vignettes" directory and they should build fine.  If you want to test how they look to the user, just use dev tools to install the package with the `build_vignettes` flag set to true.  Assuming your working directory is the same as the library, you can check it out with this code:

```R
library(devtools)
install(".",build_vignettes = TRUE)
library(EcoSimR)
vignette(package = "EcoSimR")
vignette("nicheOverlapVignette")
```

**Comment by ngotelli** [comment]
:+1:

**Comment by emhart** [comment]
@ngotelli and @amellison17 Docs page is essentially complete save a few tweaks.  I'll need to get the examples to run, but  that's it.  I had to write some extensions to `staticdocs` to customize our page so it''s mostly automated, but it's probably best if you just route your changes through me via issues.

Check it out here: http://docs.ecosimr.org
