### ISSUE TITLE
Suspicious results

### ISSUE THREAD

**Issue by ngotelli** [GotelliLab/EcoSimR#50]
`sim2` in co-occurrence should be giving unusually low score not high if species are reshuffled equiprobably among sites. check with plot of simulated data.

Numbers for observed and mean of simulated from size overlap with algo=`size_gamma` look incorrect. Need to check against plot.

**Comment by emhart** [comment]
@ngotelli any progress on this?  We're otherwise close to having all of the bugs worked out for a first release.

**Comment by ngotelli** [comment]
Both of these algorithms seem to be behaving properly. And the co-occurrence results match up with output from the original EcoSim program. We should set the default algo for co-occurrence to `sim9`.
