### ISSUE TITLE
Sim9 no longer works properly

### ISSUE THREAD

**Issue by emhart** [GotelliLab/EcoSimR#57]
With the new PR, it's broken the sim9 fxn and all the plotting.  Burnin no longer seems to work.  Not sure if the whole algo is busted or if it's just the plotting.

**Comment by davharris** [comment]
Sorry, is this a bug with my code from #55 and #56? If so, I can dig in and see what I broke.

**Comment by emhart** [comment]
I actually tracked it down @davharris , turns out I didn't notice it until I did some tests on your PR.  It actually cropped up earlier from a typo.
