### ISSUE TITLE
Change row name stripping

### ISSUE THREAD

**Issue by emhart** [GotelliLab/EcoSimR#60]
Initially it was possible that a user might accidentally import a data with row names as one of the columns resulting in a text only data frame.  However it was set to true by default, so it would be easy to just lop off a column of data.  Instead I've implemented code to just handle this automagically...

**Comment by ngotelli** [comment]
That's a nice addition. In fact, I made precisely that mistake when I
first analyzed some random data sets I had simulated to test Co-occurrence.

    N.

    Quoting Edmund Hart <notifications@github.com>:
>
> Initially it was possible that a user might accidentally import a  
> data with row names as one of the columns resulting in a text only  
> data frame. However it was set to true by default, so it would be  
> easy to just lop off a column of data. Instead I've implemented code  
> to just handle this automagically...
>
> —
>    Reply to this email directly or view it on GitHub[1].
>  
>
>

 
********************************************************
    Nicholas J. Gotelli       Office Phone: 802-656-0450
    Department of Biology     Lab Phone: 802-656-0451   
    University of Vermont     Fax: 802-656-2914
    Burlington, VT 05405      e-mail: ngotelli@uvm.edu
    ********************************************************
    Home Page (with manuscript pdfs):
http://www.uvm.edu/~ngotelli/homepage.html

    Musician's Corner (with mp3s):
http://www.uvm.edu/~ngotelli/musicpage/music.html

    NEW: EcoSimR (free software for null model analysis):
http://www.uvm.edu/~ngotelli/EcoSim/EcoSim.html
    ********************************************************



Links:
------
[1] https://github.com/GotelliLab/EcoSimR/issues/60
