### ISSUE TITLE
EcoSimR ready to post to CRAN?

### ISSUE THREAD

**Issue by ngotelli** [GotelliLab/EcoSimR#64]
@emhart and @amellison17

I have finished all of my documentation on the existing files. Ted, please look through it and make sure it is OK. I had trouble with some of the formatting for the data file descriptions (the text is repeated in title font), but I think everything is complete, and it did compile correctly in `dev_tools`. 

I will hold off on editing the homepage and creating a new webpage until we get this posted.

Ted, is there anything further for me to do?

**Comment by emhart** [comment]
Hi @ngotelli Yes, the package is set for release.  I've updated the main [webpage](http://ecosimr.org) and the [docs](http://docs.ecosimr.org).  I tagged a release and submitted it to CRAN.  I'll let you know as soon as it's posted.

**Comment by ngotelli** [comment]
Hi @emhart . Hey, that's terrific! I will soon write up a comprehensive enhancement list of things to improve for the next version. For now, I will start pulling together some scripts for my Switzerland trip. :zap:
