### ISSUE TITLE
`appveyor.yml` is being added to pkg tarball

### ISSUE THREAD

**Issue by gavinsimpson** [GotelliLab/EcoSimR#67]
Checking package (under R-devel but R-patched should be picking this up too) results in:

```
* checking top-level files ... NOTE
Non-standard file/directory found at top level:
  ‘appveyor.yml’
```

To fix this, add an `.Rbuildignore` file with following content:

```
appveyor.yml
```

you could add the following too

```
.gitignore
LICENSE
^\.travis\.yml$
```

but R must already be ignoring those by default, though it is complaining about `.travis.yml` in a separate, earlier note:

```
* checking for hidden files and directories ... NOTE
Found the following hidden files and directories:
  .travis.yml
These were most likely included in error. See section ‘Package
structure’ in the ‘Writing R Extensions’ manual.

CRAN-pack does not know about
  .travis.yml
```

**Comment by emhart** [comment]
Thanks @gavinsimpson 

I just pushed up a `.Rbuildignore` to the repo.  Did you test the package on your build system?

**Comment by gavinsimpson** [comment]
Yep, just needed to update R-devel first. You'll take care of all NOTEs except

```
* checking CRAN incoming feasibility ... NOTE
```

and you can't do, nor need to do, anything about as your Maintainer info and `LICENSE` file are in order.

I checked this with the `--as-cran` option, which turns on checks that CRAN runs.

**Comment by emhart** [comment]
Thanks.  Ok  I'll try submitting to CRAN again.

**Comment by gavinsimpson** [comment]
With the new `.Rbuildignore` you should be good to go for CRAN. Nothing wrong that i can see under R-devel. Do use the optional comment box when submitting via the web interface to explain that you've fixed the problems and checked under R-Devel on Linux (and I presume Windows) and only NOTE is the CRAN Incoming Feasibility check.
