### ISSUE TITLE
New functions on EcoSimR

### ISSUE THREAD

**Issue by drcala** [GotelliLab/EcoSimR#74]
Hi again! I need to use the co-ocurrence models but I would like to use it with other metrcis rather than the C-score, or the variance ratio. These metrics are ratios related to limiting similarity, guild proportionality and niche limitation (eg. Götzenberger et al. 2012). Can I just put the new function as an argument the cooc_null_model function? If not, what can I do?

Thank you in advance

**Comment by ngotelli** [comment]
Thanks for your query. Please read the vignette `nullModelPlug-Ins` that is included with the documentation in the `EcoSimR` package. It gives detailed instructions on how to use the co-occurrence models with user-defined metrics.

**Comment by drcala** [comment]
Thank you

**Comment by ngotelli** [comment]
Good, I hope that you can integrate  your new code with EcoSimR.
